name: DAST – ZAP Baseline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"   # 매일 03:00 KST
  push:
    branches: [ main ]

jobs:
  zap-baseline:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: https://${{ secrets.DOMAIN }}
          rules_file_name: .zap/rules.tsv
          cmd_options: >-
            -m 5         # passive + 5분
            -a           # alpha 규칙 포함(원치 않으면 제거)
          allow_issue_writing: false
          artifact_name: zap-scan          # ← 언더스코어 대신 하이픈
          fail_action: false               # 안정화 후 true

      # HTML/JSON 리포트는 액션이 자동으로 아티팩트로 올림.
      # 추가로 SARIF 올리고 싶다면:
      - name: Upload empty SARIF (optional placeholder)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: .github/empty.sarif
