name: DAST – ZAP Baseline

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 18 * * *"   # 매일 03:00 KST (UTC 18:00)

jobs:
  zap-baseline:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Check out
        uses: actions/checkout@v4

      # 룰 파일이 레포에 없을 경우 생성(있으면 그대로 사용)
      - name: Ensure .zap/rules.tsv exists
        run: |
          mkdir -p .zap
          if [ ! -f .zap/rules.tsv ]; then
            cat > .zap/rules.tsv <<'TSV'
                # pluginId<TAB>action<TAB>newConfidence(optional)
                10035  WARN
                10020  WARN
                10021  WARN
                10038  WARN
                10063  WARN
                10049  IGNORE
                10015  IGNORE
                90004  IGNORE
                TSV
          fi
          echo "---- .zap/rules.tsv ----"
          cat .zap/rules.tsv

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: https://${{ secrets.DOMAIN }}
          rules_file_name: .zap/rules.tsv
          # 5분 크롤링, 알파 룰 포함(원치 않으면 -a 제거)
          cmd_options: "-m 5 -a"
          # artifact 이름: 영문+숫자만 (문제 회피)
          artifact_name: zapscan
          # 안정화 후 true로 바꿔 '게이트'로 사용 가능
          fail_action: false

      # 내부 업로드가 삐끗해도 백업으로 수동 업로드
      - name: Upload ZAP reports (manual fallback)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zapscan_files
          path: |
            report_html.html
            report_md.md
            report_json.json
          retention-days: 7
