name: Security – DAST (ZAP Baseline)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * 1"   # 매주 월요일 00:00 UTC (KST 월 09:00)

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      TARGET: https://${{ secrets.DOMAIN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # rules.tsv = <id>\t<level>\t<note>  (탭 필수, 최소 3토큰)
      - name: Prepare ZAP rules.tsv
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p .zap
          : > .zap/rules.tsv
          printf '10015\tWARN\tCache-Control tune when behind CDN\n' >> .zap/rules.tsv
          printf '10020\tWARN\tAdd X-Frame-Options/frame-ancestors later\n' >> .zap/rules.tsv
          printf '10021\tWARN\tAdd X-Content-Type-Options nosniff\n' >> .zap/rules.tsv
          printf '10035\tWARN\tEnable HSTS after HTTPS stable\n' >> .zap/rules.tsv
          printf '10036\tWARN\tHide Server header via nginx\n' >> .zap/rules.tsv
          printf '10038\tWARN\tBaseline CSP then tighten\n' >> .zap/rules.tsv
          printf '10049\tWARN\tTune cacheability by route\n' >> .zap/rules.tsv
          printf '10063\tWARN\tAdd Permissions-Policy\n' >> .zap/rules.tsv
          printf '90004\tWARN\tSpectre isolation (COOP/COEP)\n' >> .zap/rules.tsv
          echo "---- .zap/rules.tsv (showing tabs as ^I) ----"
          cat -v .zap/rules.tsv

      # 컨테이너가 /zap/wrk/* 파일 쓰는 권한 문제 줄이기
      - name: Loosen workspace perms for container
        run: sudo chmod -R a+rwX .

      - name: ZAP Baseline Scan (reports only)
        uses: zaproxy/action-baseline@v0.12.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: ${{ env.TARGET }}
          rules_file_name: '.zap/rules.tsv'
          # 내부 아티팩트 업로드 비활성화(400 회피)
          artifact_name: ''
          # 5분 크롤링 + alpha 룰 포함, 리포트 파일 지정
          cmd_options: >-
            -m 5 -a
            -J report_json.json
            -w report_md.md
            -r report_html.html

      - name: Upload ZAP reports (manual)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-${{ github.run_id }}
          path: |
            report_json.json
            report_md.md
            report_html.html
          retention-days: 14
