name: Security – DAST (ZAP Baseline)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"   # 매주 월요일 00:00 UTC
  push:
    branches: [ main ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write          # (선택) 이슈 코멘트/생성에 쓰려면
      actions: read
    env:
      TARGET: https://${{ secrets.DOMAIN }}   # 예: https://jongyun.mjsec.kr

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # rules.tsv 생성 (탭으로 3토큰 이상, printf가 \t를 탭으로 변환)
      - name: Prepare ZAP rules.tsv (make header-findings WARN not FAIL)
        run: |
          mkdir -p .zap
          : > .zap/rules.tsv
          printf '10015\tWARN\tCache-Control tuning while behind CDN\n' >> .zap/rules.tsv
          printf '10020\tWARN\tX-Frame-Options / frame-ancestors to be added\n' >> .zap/rules.tsv
          printf '10021\tWARN\tAdd X-Content-Type-Options: nosniff\n' >> .zap/rules.tsv
          printf '10035\tWARN\tEnable HSTS after TLS stabilized\n' >> .zap/rules.tsv
          printf '10036\tWARN\tHide Server header via Nginx\n' >> .zap/rules.tsv
          printf '10038\tWARN\tAdd CSP header (baseline)\n' >> .zap/rules.tsv
          printf '10049\tWARN\tCacheability to be tuned\n' >> .zap/rules.tsv
          printf '10063\tWARN\tAdd Permissions-Policy\n' >> .zap/rules.tsv
          printf '90004\tWARN\tSpectre isolation (COOP/COEP)\n' >> .zap/rules.tsv

      # 컨테이너가 리포트/AF yaml 쓰기 실패하는 경고 줄이기
      - name: Loosen workspace perms for ZAP container (optional)
        run: sudo chmod -R a+rwX .

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: ${{ env.TARGET }}
          rules_file_name: '.zap/rules.tsv'
          allow_issue_writing: 'false'     # 원하면 true
          artifact_name: 'zapscan'         # 영문/숫자만(하이픈 피하기)
          cmd_options: >-
            -J report_json.json
            -w report_md.md
            -r report_html.html
            -m 5
            -a

      # 리포트 아티팩트로 보관
      - name: Upload ZAP reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zapscan-reports
          path: |
            report_json.json
            report_md.md
            report_html.html
          retention-days: 14
